openapi: 3.0.0
info:
  title: Pizza Webshop API Documentation
  description: Swagger API documentation for Pizza Webshop application
  version: 1.0.0

servers:
  - url: http://localhost:8000

tags:
  - name: userHandling
    description: Operations about user
  - name: orderHandling
    description: Everything about Orders
  - name: dataHandling
    description: Access to Product data
  - name: auth
    description: Authentication

paths:
  /api/login:
    post:
      tags:
        - userHandling
      description: Signs in a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginCredentials"

      responses:
        200: # status code
          description: User signed in successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccessToken"

        400: # status code
          description: Invalid request
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/ArrayOfErrorMessages"
                  - $ref: "#/components/schemas/ErrorMessage"

        500: # status code
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"

  /api/register:
    post:
      tags:
        - userHandling
      description: Signs up a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegistrationData"

      responses:
        200: # status code
          description: User signed up successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessMessage"

        400: # status code
          description: Invalid request
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/ArrayOfErrorMessages"
                  - $ref: "#/components/schemas/ErrorMessage"

        500: # status code
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"

  /api/password:
    post:
      tags:
        - userHandling
      description: Setting a new password for the given user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewPasswordData"

      responses:
        200: # status code
          description: User changed/set his/her password successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessMessage"

        400: # status code
          description: Invalid request
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/ArrayOfErrorMessages"
                  - $ref: "#/components/schemas/ErrorMessage"

        500: # status code
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"

  /api/reset:
    post:
      tags:
        - userHandling
      description: Setting a reset property for the given user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ResetPasswordData"

      responses:
        200: # status code
          description: Reset property of the given user has been set successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessMessage"

        400: # status code
          description: Invalid request
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/ArrayOfErrorMessages"
                  - $ref: "#/components/schemas/ErrorMessage"

        500: # status code
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"

  /api/google:
    post:
      tags:
        - userHandling
      description: Signing up or in the user with google
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GoogleLoginData"

      responses:
        200: # status code
          description: User signed up/in successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccessToken"

        400: # status code
          description: Invalid request
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/ArrayOfErrorMessages"
                  - $ref: "#/components/schemas/ErrorMessage"

        500: # status code
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"

  /api/confirm:
    post:
      tags:
        - userHandling
      description: Confirming user registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ConfirmRegistrationData"

      responses:
        200: # status code
          description: User registration has been confirmed successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccessToken"

        400: # status code
          description: Invalid request
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/ArrayOfErrorMessages"
                  - $ref: "#/components/schemas/ErrorMessage"

        500: # status code
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"

  /api/loaduser:
    get:
      tags:
        - userHandling
      security:
        - pizzaWebshopAuth: []
      description: Returns the user data if the user is authenticated
      responses:
        200: # status code
          description: The user data has been returned successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserData"
        400: # status code
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"

        401: # status code
          description: Unauthenticated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"

        500: # status code
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"

  /api/order:
    post:
      tags:
        - orderHandling
      security:
        - pizzaWebshopAuth: []
      description: Sending an order request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderData"

      responses:
        200: # status code
          description: Order has been saved in database successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessMessage"

        400: # status code
          description: Invalid request
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/ArrayOfErrorMessages"
                  - $ref: "#/components/schemas/ErrorMessage"

        401: # status code
          description: Unauthenticated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"

        500: # status code
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"

  /api/orders:
    get:
      tags:
        - orderHandling
      security:
        - pizzaWebshopAuth: []
      description: Returns the orders of the user if the user is authenticated
      responses:
        200: # status code
          description: The orders data has been returned successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ArrayOfOrders"

        401: # status code
          description: Unauthenticated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"

        500: # status code
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"

components:
  securitySchemes:
    pizzaWebshopAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT # optional, arbitrary value for documentation purposes

  schemas:
    OrderData:
      type: object
      required:
        - name
        - tel
        - email
        - address
      properties:
        name:
          type: string
        email:
          type: string
        tel:
          type: string
        address:
          type: string
        cart:
          type: object
          properties:
            pizza:
              type: object
            topping:
              type: object

    OrderItem:
      type: object
      required:
        - name
        - tel
        - email
        - address
      properties:
        name:
          type: string
        email:
          type: string
        tel:
          type: string
        address:
          type: string
        date:
          type: string
          format: date-time
        cart:
          type: object
          properties:
            pizza:
              type: array
                items:
                  $ref: "#/components/schemas/CartItem"
            topping:
              type: array
                items:
                  $ref: "#/components/schemas/CartItem"
    CartItem:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        quantity:
          type: integer
        price:
          type: integer

    UserData:
      type: object
      required:
        - name
        - photo
      properties:
        name:
          type: string
        photo:
          type: string

    LoginCredentials:
      type: object
      required:
        - password
        - email
      properties:
        email:
          type: string
        password:
          type: string

    RegistrationData:
      type: object
      required:
        - name
        - password
        - email
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string

    ConfirmRegistrationData:
      type: object
      required:
        - code
        - email
      properties:
        code:
          type: string
        email:
          type: string

    GoogleLoginData:
      type: object
      required:
        - code
      properties:
        code:
          type: string

    ResetPasswordData:
      type: object
      required:
        - email
      properties:
        email:
          type: string

    NewPasswordData:
      type: object
      required:
        - code
        - password
        - email
      properties:
        code:
          type: string
        email:
          type: string
        password:
          type: string

    ArrayOfErrorMessages:
      type: array
        items:
          $ref: "#/components/schemas/ErrorMessageItem"

    ArrayOfOrders:
      type: array
        items:
          $ref: "#/components/schemas/OrderItem"

    ErrorMessage:
      type: object
      required:
        - msg
      properties:
        msg:
          type: string

    Token:
      type: object
      required:
        - token
      properties:
        token:
          type: string
